language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

# pytest-codestyle ; python_version >= "3.5"
# pytest-mypy ; platform_python_implementation != "PyPy" and python_version >= "3.5"
# pytest-runner

install:
    - pip install pytest-codestyle
    - pip install pytest-mypy
    - python setup.py install
script:
    - py.test arpeggio/tests
